version: '3.8'

services:
  http:
    build:
      dockerfile: DockerFilehttp
    ports:
      - "8000:8000"
    volumes:
      - shared-volume:/template/app/reports
    depends_on:
      - flask

  flask:
    build:
      dockerfile: DockerfileFlask
    ports:
      - "5000:5000"
    volumes:
      - shared-volume:/template/app/reports

volumes:
  shared-volume:      
